# Copyright 2026 The KubeEdge Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Export changed example detection results for GitHub Actions."""

from __future__ import print_function

import argparse
import json
import os
from pathlib import Path
from typing import Optional, Sequence


def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Export changed example detection results to GitHub Actions."
    )
    parser.add_argument(
        "--report",
        default="changed_examples.json",
        help="Path to the JSON report generated by detect_changed_examples.py.",
    )
    return parser.parse_args(argv)


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)
    report = json.loads(Path(args.report).read_text(encoding="utf-8"))

    print("run_all={}".format(report["run_all"]))
    print("changed_files={}".format(len(report["changed_files"])))
    print("examples={}".format(report["examples_count"]))
    for example in report["examples"]:
        print("  - {}".format(example))

    output_path = os.environ.get("GITHUB_OUTPUT")
    if output_path:
        with Path(output_path).open("a", encoding="utf-8") as handle:
            print(
                "run_all={}".format("true" if report["run_all"] else "false"),
                file=handle,
            )
            print(
                "examples_json={}".format(json.dumps(report["examples"])),
                file=handle,
            )
            print("examples_count={}".format(report["examples_count"]), file=handle)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
